export const ENV_VARIABLES = {
  DATABASE: {
    host: 'DB_HOST',
    port: 'DB_PORT',
    user: 'DB_USER',
    password: 'DB_PASSWORD',
    database: 'DB_NAME',
    poolSize: 'DB_POOL_SIZE',
  },
  GEMINI: {
    API_KEY: 'GEMINI_API_KEY',
    COST_INPUT_PER_MILLION: 'GEMINI_COST_INPUT_PER_MILLION',
    COST_OUTPUT_PER_MILLION: 'GEMINI_COST_OUTPUT_PER_MILLION',
    COST_EMBEDDING_PER_MILLION: 'GEMINI_COST_EMBEDDING_PER_MILLION',
    GENERATION_MODEL: 'GEMINI_GENERATION_MODEL',
    EMBEDDING_MODEL: 'GEMINI_EMBEDDING_MODEL',
  },
  SERVER: {
    PORT: 'SERVER_PORT',
  },
  RERANKER: {
    MODEL: 'RERANKER_MODEL',
  },
  S3: {
    ENDPOINT: 'S3_ENDPOINT',
    REGION: 'S3_REGION',
    ACCESS_KEY_ID: 'S3_ACCESS_KEY_ID',
    SECRET_ACCESS_KEY: 'S3_SECRET_ACCESS_KEY',
    BUCKET_NAME: 'S3_BUCKET_NAME',
    FORCE_PATH_STYLE: 'S3_FORCE_PATH_STYLE',
  },
  REDIS: {
    HOST: 'REDIS_HOST',
    PORT: 'REDIS_PORT',
    USER: 'REDIS_USER',
    PASSWORD: 'REDIS_PASSWORD',
  },
  AUTH0: {
    DOMAIN: 'AUTH0_DOMAIN',
    AUDIENCE: 'AUTH0_AUDIENCE',
  },
  OLLAMA: {
    BASE_URL: 'OLLAMA_BASE_URL',
    CLASSIFIER_MODEL: 'OLLAMA_CLASSIFIER_MODEL',
    SHADOW_SAMPLE_RATE: 'OLLAMA_SHADOW_SAMPLE_RATE',
  },
} as const;
