export const SEARCH_DEFAULTS = {
  TOP_K: 3,
  CANDIDATE_K: 20,
  RERANK_POOL_K: 10,
  MAX_DISTANCE: 0.5,
} as const;

export const MULTI_HOP_DEFAULTS = {
  CONFIDENCE_THRESHOLD: 0,
  MAX_FOLLOW_UP_QUERIES: 2,
} as const;
